# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

clickhouse_default: &clickhouse_default
  adapter: clickhouse
  migrations_paths: db/clickhouse_migrate

development:
  primary:
    <<: *default
    database: evolution_development
  clickhouse:
    <<: *clickhouse_default
    database: evolution_development

test:
  primary:
    <<: *default
    database: evolution_test
  clickhouse:
    <<: *clickhouse_default
    database: evolution_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  clickhouse:
    <<: *clickhouse_default
    database: evolution_production
    host: <%= ENV["CLICKHOUSE_HOST"] %>
    password: <%= ENV["CLICKHOUSE_PASSWORD"] %>
